gut tells you if its up to date
bitwes/Gut pull request #274
Opened 2021-02-10 21:07 UTC by astrale-sharp

#254

The message appears at the very end of the run
every error is ignored ;)

2021-02-10 21:11 UTC, astrale-sharp commented
![gut1](https://user-images.githubusercontent.com/53686698/107572617-cbc3e900-6bec-11eb-8455-8468e1f8d34a.png)

![gut2](https://user-images.githubusercontent.com/53686698/107572629-cebed980-6bec-11eb-8e48-444da7c0b811.png)

Maybe I should jump a line before the message?

2021-02-10 21:25 UTC, bitwes commented
Sweet!  Two small tweaks and I'll start the review

* I think we can  skip telling  the user they are  up  to date.  The less they need to read the better.
* Change the "new version" message to be:
```
GUT version <whatever> is now available.
```

2021-02-10 21:35 UTC, astrale-sharp commented
Done :) you want me to squash them in one commit?

2021-02-11 17:00 UTC, bitwes requested changes
Break the code out of `_ready` into  a request method called from `_ready`.
There should at least be some tests to make sure that the handling of the response does not  cause errors.  Put these tests in `test/unit/test_utils.gd`.

There are also two bugs that need to be addressed.:

1.  If there is no internet connection then errors are printed in the output:
```
ERROR: _resolve_hostname: getaddrinfo failed! Cannot resolve hostname.
   At: drivers/unix/ip_unix.cpp:112.
[INFO]:  using [/Users/butchwesley/Library/Application Support/Godot/app_userdata/Gut] for temporary output.
Godot version:  3.2.3
GUT version:  7.1.0
ERROR: call: Error parsing JSON at line 0:
   At: modules/gdscript/gdscript_functions.cpp:1268.
```

2.   If the response does  not contain `html_url` then  GUT  hangs.  This should also be ignored.  You can  simulate this with the existing code by taking the last letter off of the url.
```
Debugger Break, Reason: 'Invalid get index 'html_url' (on base: 'Dictionary').'
*Frame 0 - res://addons/gut/utils.gd:121 in function '_http_request_completed'
Enter "help" for assistance.
```

2021-02-11 17:24 UTC, bitwes commented
Also add a bullet point to the top of CHANGES.md

2021-02-11 18:26 UTC, astrale-sharp commented
I've done some research but im not sure this error can be ignored `ERROR: _resolve_hostname: getaddrinfo failed! Cannot resolve hostname.
   At: drivers/unix/ip_unix.cpp:112.`

there is discussion about this [here](https://github.com/godotengine/godot/issues/22489)

2021-02-13 20:06 UTC, bitwes requested changes

2021-02-13 20:06 UTC, bitwes commented on test/unit/test_autofree.gd
> +	assert_false(false)
revert this change.

2021-02-14 21:08 UTC, bitwes approved these changes

2021-02-14 21:10 UTC, merged