4.0 DirectoryCtrl::set_text Infinite Loop Fix
bitwes/Gut pull request #400
Opened 2022-08-20 05:24 UTC by Tim-Fronsee

### Summary

#### Bug

An infinite loop occurs while attempting to initialize `gut_config_gui` due to `set_text` calling into itself via `text = t`, resulting in an editor crash while opening a project with the plugin enabled.  In case it's relevant, I'm running the editor and plugin on Windows 10.

Interestingly, I received no error messages (such as an out of memory error / exception) from the engine while trying to nail down the source, even when running the editor in verbose mode.  

#### Fix 

I removed the `set_text` function in `DirectoryCtrl`, migrating the logic into the setter. 

#### Extras

I changed the `add_child` calls to `call_deferred` in `DirectoryCtrl::_ready` as I believe this is the preferred method for adding children in `_ready`.

2022-08-20 14:27 UTC, bitwes requested changes
Good find.  I've fixed a number of these in other places.  This new `set`/`get` is nice, but when there is a backing variable it loses its mind.

Although this is an "experiments" branch, it's starting to have enough changes that it might become the real thing.  So, in this case I would rather just make the "text" property be a wrapper around `_txt_path.text` via the `get` and `set` (as per my requested changes).

Thanks for all the PRs.  It has been very helpful.

2022-08-20 14:27 UTC, bitwes commented on addons/gut/gui/gut_config_gui.gd
>  			return get_text()
Change this to `return _txt_path.text`

2022-08-20 14:27 UTC, bitwes commented on addons/gut/gui/gut_config_gui.gd
> +			text = val
Remove the assignment this assignment.  It will make it clear that this is just a wrapper around `_txt_path.text`.

2022-08-20 14:27 UTC, bitwes commented on addons/gut/gui/gut_config_gui.gd
>  	func get_text():
Delete this method since the `get():` above will return this value.

2022-08-20 14:29 UTC, bitwes commented
I forgot to add, do you have any info on the `call_deferred` for adding children in `_ready`?  I have not heard this before.

2022-08-21 04:18 UTC, Tim-Fronsee commented
> I forgot to add, do you have any info on the `call_deferred` for adding children in `_ready`? I have not heard this before.

I've seen this error in my own plugin when calling `add_child` from `_enter_tree`, but I was not seeing it from Gut.  

There's an existing [forum post](https://godotengine.org/qa/28050/parent-node-is-busy-setting-up-children-add_node-failed) featuring the error, for which I based my assumption (perhaps incorrectly) regarding `_ready`.  

Admittedly, this change expands the PR beyond addressing the infinite loop.  If you'd like, I will revert the `add_child` changes along with the requested changes.

2022-08-21 17:13 UTC, bitwes approved these changes

2022-08-21 17:15 UTC, bitwes commented
>There's an existing [forum post](https://godotengine.org/qa/28050/parent-node-is-busy-setting-up-children-add_node-failed) featuring the error, for which I based my assumption (perhaps incorrectly) regarding _ready.

I have seen that error before.  If it shows up then we should address it.  I agree with the revert.

2022-08-21 17:16 UTC, merged