WIP: Bugfix/i578
bitwes/Gut pull request #587
Opened 2024-04-03 00:29 UTC by lxkarp

The hope here is to resolve #578

I haven't done any cleanup as suggested by @bitwes over in the issue thread. But the fix he suggested works just fine, and this PR is evidence of that.

2024-04-03 02:31 UTC, lxkarp commented
I think this may not correctly trigger `is_action_just_pressed`. I'll make another test to validate this tomorrow.

2024-04-04 17:08 UTC, Kulkodar commented
Thank you for taking the initiative, with the changes all my tests are working again. It seems that ´is_action_just_pressed´ is working.

2024-04-04 20:28 UTC, lxkarp commented
I found that the problem with `is_action_just_pressed` -- for me at least -- is that it doesn't work in `_process` but it does work in `_physics_process`

2024-04-22 19:28 UTC, bitwes requested changes
Thanks for the PR.  The code change looks good.  I'd like some additional testing to verify that the `Input.is_action_just_*` methods work as expected.  If you change the `InputSingletonTracker` to the code below, you should be able to make assertions that they are working.

**NOTE** When I tried verifying that `is_action_just_pressed` was working I had to add a leading `wait_frames` for the `InputSingletonTracker` to detect the frame when the action goes down
``` gdscript
_sender.wait_frames(1).action_down("jump").hold_for('10f')
await wait_for_signal(_sender.idle, 5)
```

Here's my take on `InputSingletonTracker`
```gdscript
class InputSingletonTracker:
	extends Node
	var pressed_frames = []
	var just_pressed_count = 0
	var just_released_count = 0

	var _frame_counter = 0

	func _process(delta):
		_frame_counter += 1

		if(Input.is_action_just_pressed("jump")):
			just_pressed_count += 1

		if(Input.is_action_just_released("jump")):
			just_released_count += 1

		if Input.is_action_pressed("jump"):
			pressed_frames.append(_frame_counter)

```

2024-07-09 20:39 UTC, merged

2024-07-09 20:39 UTC, bitwes commented
Hey @lxkarp.  @Edearth added the requested tests so I'm merging this PR for street cred, then I'll merge theirs.  Thanks!