Update is_almost_eq() to use built-in vector comparison
bitwes/Gut pull request #668
Opened 2024-11-16 17:27 UTC by onegm

Using [Vector.max()](https://docs.godotengine.org/en/stable/classes/class_vector2.html#class-vector2-method-max) and Vector.min() allows using is_almost_eq() with any vector (2, 3, or 4) and simplifies the function.

2024-11-29 23:19 UTC, bitwes commented
This is a lot cleaner.  Thanks.  Add the following tests `test/unit/test_test.gd` next to the other `assert_almost_eq` tests and I'll merge it:
```gdscript
	func test_passes_with_vecor4s_within_range():
		gr.test.assert_almost_eq(Vector4(1.0, 2.0, 3.0, 1.0), Vector4(1.0, 1.0, 1.0, 1.0), Vector4(2.0, 2.0, 2.0, 2.0), "Should pass")
		assert_pass(gr.test)
		
	func test_fails_with_vector4_outside_range():
		gr.test.assert_almost_eq(Vector4(1.0, 2.0, 3.0, 1.0), Vector4(9.0, 1.0, 1.0, 1.0), Vector4(2.0, 2.0, 2.0, 2.0), "Should pass")
		assert_fail(gr.test)
```

2024-11-29 23:20 UTC, bitwes requested changes
Add these to `test/unit/test_test.gd`
``` gdscript
	func test_passes_with_vecor4s_within_range():
		gr.test.assert_almost_eq(Vector4(1.0, 2.0, 3.0, 1.0), Vector4(1.0, 1.0, 1.0, 1.0), Vector4(2.0, 2.0, 2.0, 2.0), "Should pass")
		assert_pass(gr.test)
		
	func test_fails_with_vector4_outside_range():
		gr.test.assert_almost_eq(Vector4(1.0, 2.0, 3.0, 1.0), Vector4(9.0, 1.0, 1.0, 1.0), Vector4(2.0, 2.0, 2.0, 2.0), "Should pass")
		assert_fail(gr.test)
```

2024-12-01 17:04 UTC, onegm commented
Of course, the tests testing tests! Lol

I went with the assumption that the second message had a typo. I'm assuming the failing test message should say "should fail"

2024-12-05 16:53 UTC, bitwes requested changes
I apologize, I assumed that the old code wouldn't handle Vector4s at all, so I figured one passing and one failing test would be enough to spot check vector4s.  I was wrong, the two tests I requested pass with the old code.  This one additional does fail with the old code and passes with the new code.
```
	func test_fails_when_vector4_y_outside_range():
		gr.test.assert_almost_eq(Vector4(1.0, 2.0, 99.0, 1.0), Vector4(1.0, 1.0, 1.0, 1.0), Vector4(2.0, 2.0, 2.0, 2.0), "Should fail")
		assert_fail(gr.test)
```
I know this PR intended to simplify logic, but it really is adding support for Vector4s, so I want to make sure that doesn't get lost in the future.

2024-12-05 18:31 UTC, onegm commented
Ah yes, I see what's happening. I should've made sure the tests failed. I added the last test and also made a small modification from the original PR. 
```GDScript
	if typeof(got) in [TYPE_VECTOR2, TYPE_VECTOR3, TYPE_VECTOR4]:
		result = got.clamp(lower, upper) == got
```
using `clamp()` instead of min & max seems clearer.

2024-12-05 18:38 UTC, bitwes approved these changes
Looks good.

2024-12-05 18:38 UTC, merged